### ISSUE TITLE
Documentation: Redesign

### ISSUE THREAD

**Issue by SirMallard** [SirMallard/Iris#65]
The current documentation is fairly limited and does not provide a good explanation of many of the important aspects of using Iris. A general overhaul of information and better tutorials and teaching is needed for the documentation so that it goes beyond just being an API info section.

**Comment by warprbx** [comment]
I agree, had to look in the demo to understand it haha

**Comment by SirMallard** [comment]
I've been working on improving the overall documentation which is visible on the docs branch at the moment. It will take a bit of time to update everything and include enough additional information to properly explain how Iris works and the best ways to integrate it into a game.
