### ISSUE TITLE
Iris.TabBar, Iris.Tab

### ISSUE THREAD

**Issue by warprbx** [SirMallard/Iris#71]
A tab selection in the menu bar would be useful, something that lets me sort of "clear" the window whenever I choose it.

Here's a example ;

I want 3 tabs

Player Physic Testing --> Game Physics Testing --> Settings (right of the menu bar) --- the current tab will be white and the ones that aren't will be grayed out 

and if i use just the collapsing headers for tabs, it will get overcrowded, and i have a diff purpose for them. Sure, I can use multiple windows for each but I have a ton of info on just 1 window and if i spread them out im worried it will be hard for me to control, this would make it much easier and better for me to organize 

A system in which I can choose those tabs would be really nice

**Comment by SirMallard** [comment]
Tabs is another feature which would be good to add but is not currently implemented. The best option we have at the moment is what the styling window does with radio buttons.

**Comment by warprbx** [comment]
Thanks! Forgot about them
