### ISSUE TITLE
Reactive Mouse Icon

### ISSUE THREAD

**Issue by Michael-48** [SirMallard/Iris#76]
Currently, Iris has no effect on the mouse icon, meaning there is little feedback given to the user when hovering over a scrollable item, stretchable item, input field, or button. I'm proposing a new utility configuration option `UseMouseIcons` which when enabled, Iris will write to UserInputService.MouseIcon with the appropriate icon from `content\textures\Cursors` contextually.

I'm not sure what cascading effects could stem from this change, and I'm also not sure what effects it may have in other contexts (think BillboardGui, SurfaceGui, and plugins)

**Comment by SirMallard** [comment]
I think this would be a good addition, however, I'm not so sure about what would happen if a user adds their own interactions. For example, you could imagine an example where we cache the last icon, change it, wait until the mouse leaves and set it to the cache, only to find the user has changed it elsewhere and we have messed it up for them. I don't know how we could fix this?
