### ISSUE TITLE
Window Resizing from the Bottom Left

### ISSUE THREAD

**Issue by Michael-48** [SirMallard/Iris#77]
The Window widget is almost entirely unchanged from the original release of Iris, which is surprising. Its the 3rd widget I ever wrote, and as a consequence of laziness i opted not to include a feature which is present in Dear ImGui. There is a blue dragging triangle on the bottom left which is identical to the one on the bottom right, but it is normally transparent unless hovered over by the cursor.

Admittedly, this is trivial— but it would be nice to maintain as many similarities to Dear ImGui as possible.

**Comment by SirMallard** [comment]
Alongside this, Dear ImGui features a blue line highlight for resizing any edge. It would be a good visual indicator that you can drag from that. I've found the side resizing behaviour is inconsistent.

**Comment by SirMallard** [comment]
I've added this functionality in 223848d33d060a88d81667b691bccca73a360d3e.
